### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by loveJasmine** [cheng6076/LSTM-Autoencoder#1]
envy@ub1404:~/os_pri/github/LSTM-Autoencoder$  th LSTMAutoencoder.lua
one-time setup: preprocessing input train/valid/test files in dir: corpus	
Processing text into tensors...	
/home/envy/torch/install/bin/luajit: ./util/BatchLoaderC.lua:98: attempt to index local 'f' (a nil value)
stack traceback:
	./util/BatchLoaderC.lua:98: in function 'text_to_tensor'
	./util/BatchLoaderC.lua:22: in function 'create'
	LSTMAutoencoder.lua:61: in main chunk
	[C]: in function 'dofile'
	...envy/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406260
envy@ub1404:~/os_pri/github/LSTM-Autoencoder$

**Comment by cheng6076** [comment]
There is sth wrong with your data dir. Please make sure there is a backslash behind, such as /data/
