### ISSUE TITLE
How can I obtain the *.t7 data/model files

### ISSUE THREAD

**Issue by ruohoruotsi** [cheng6076/LSTM-Autoencoder#2]
I found some train, test and valid txt files from the pennbrook corpus and vocab.t7 from karpathy's tiny Shakespeare but I'm not sure how to obtain {data, mask}.t7 

Thanks in advance 

```
> local tensor_file = path.join(data_dir, 'data.t7')
> local mask_file = path.join(data_dir, 'mask.t7')
```

**Comment by cheng6076** [comment]
Hi, the .t7 files are generated by the code automatically

2016-07-20 20:32 GMT-04:00 Ruoho Ruotsi <notifications@github.com>:

**Comment by ruohoruotsi** [comment]
Hi, thanks, I actually submitted this issue on my phone and I meant to do it for the 
https://github.com/cheng6076/Variational-LSTM-Autoencoder repo. I'll post my question there! thank you!
